### ISSUE TITLE
Internal  Heat Generation to 2D Transient conduction model

### ISSUE THREAD

**Issue by IndreshSahu** [nasa/TSAT#1]
Hi ,
First of all thank you for sharing such an insightful code in an open source platform. 
I just want to know whether there is any existing library to incorporate internal heat generation to the 2D Transient conduction Model-ADI Crank-Nicolson.
Please let me know if such libraries exist, it would be of great help

Thank you

**Comment by jkratz** [comment]
Hi,

I cannot speak about other libraries because I don't have experience with other libraries that might have such features. TSAT does not readily have the capability you are talking about, but I think it could be modified fairly easily to do what you want if you are willing to make the changes yourself. The internal heat generation would simply add another term to the heat transfer equation. The original equation is below (if it shows up, if not refer to the help file for the block in the TSAT files):

![image](https://user-images.githubusercontent.com/40473714/110024033-df4e0580-7cfb-11eb-94ed-5c411691b494.png)

The new equation would have a include a Qgen term inside the brackets. If you know what the Qgen is for each node/element or can calculate it, then you can modify the code to accept that info as a parameter or an input (whatever suits you better). The solution is found by solving a system of equations and if Qgen is not function of temperature then it will end up on the right hand side of the equation. If you are using the ADI Crank-Nicolson model it will wind up being incorporated in the C vector. If you look inside the code around line 1154 you'll see the form of the system of equations. So, I think you could do a search for anywhere C is being defined and add the heat generation term to it. You'll have to be careful to make sure the units are correct and your remember to divide be rho*Cp. The point is, make sure the Qgen term is in the proper form when you add it to the C elements. There is also an implicit solution to give an alternative to Crank-Nicolson. If I recall, I believe the implicit solution is more stable than the Crank-Nicolson method. If you open that code up and scroll to line 1134 you should see the system of equations that are being solved for there. Here you would be modifying the z vector to include a heat generation term. 

I'm sorry this feature was not included in the original code. I could revisit it at some point in the future but even if I do, it probably will not be any time soon. I developed this toolbox as a part of work that I've now moved on from and so any continued development of it will not be supported by my work. I don't want to lead you too far down a rabbit whole so if this sounds like it would a daunting or tedious task, you might keep looking for other options and I wouldn't blame you for that. With that said, I think it is possible to get the code to do what you want it to do if you take the time to understand the code and what you need to change.

**Comment by IndreshSahu** [comment]
Hi,

Thank you for such an elaborative explanation
I looked into the code and have incorporated the internal heat generation component in the C vector
I would appreciate the efforts that you have put in to write such an extensive code which can be used to solve any heat transfer problem. 

Thanks
